name: budgeting_flutter_app_v1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^0.13.5
  provider: ^6.1.2
  dartz: ^0.10.1
  shared_preferences: ^2.0.0
  font_awesome_flutter: ^10.4.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
